
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: ''
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(cLCKOqMe9ppsanYddNRTcXN30dpRGKk42YUMZh3jmXGTZDyMws/OyJSxv1i95nye)
    password: ENC(YCIUBoeyZYXbyS551Xy8JAhKYMtcTe4F1+LkabBbz0o=)
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/recommandation
    username: sa
    password:

server:
  servlet:
    encoding:
      charset: UTF-8

token:
  access_expiration_time: 8640000000
  #  1day
  refresh_expiration_time: 8640000000
  secret: user_token

jasypt:
  encryptor:
    bean: jasyptEncryptor